### ISSUE TITLE
Security vulnerability in `hp_handle_write` and `hp_handle_read`

### ISSUE THREAD

**Issue by theKidOfArcrania** [david942j/kvm-kernel-example#1]
The functions that do the hypercall for `read` and `write` does check whether if the beginning of the buffer is valid memory, but the buffer could extend into memory that is not valid. 

If the user is able to gain control of the kernel, they can at the very least leak memory that is `mmap`'d right before the the guest memory segment. If, however, the mmap'd segment is also writable, the user can also write to that memory segment, and compromise the hypervisor, by passing data as stdin, and invoking a hp read call.

**Comment by david942j** [comment]
Confirmed, thanks for report!
