### ISSUE TITLE
interrupt and exception handling

### ISSUE THREAD

**Issue by sunyulin728** [david942j/kvm-kernel-example#4]
I tried to add exception/interruput handler based on this but fail. The VM exit with "shutdown" reason.

I realize there is not gdt setup in the orignal code. But even after I add it, it still doesn't work.

Could you please let me know what I need to do beside setup gdt and idt?

**Comment by david942j** [comment]
Sorry I'm too busy to study on this for now, if you have the solution please let me know :smile:

**Comment by sunyulin728** [comment]
Thank you for help.

Yes. I have solved the problem. Just as you said, it is GDT issue. It is
from the sample code I got for KVM which has no configuration for GDT.
After I configure the GDT. The issue is solved.

Thanks,
Yulin

**Comment by david942j** [comment]
Good to know you got it working :)
