### ISSUE TITLE
Trying to run "make", receives this error.

### ISSUE THREAD

**Issue by alonwillmakeit** [david942j/kvm-kernel-example#5]
Any idea? :3  

alon @ ~/kvm-test/kvm-kernel-example - [master] $ **sudo make**
make -C hypervisor
make[1]: Entering directory '/home/alon/kvm-test/kvm-kernel-example/hypervisor'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/alon/kvm-test/kvm-kernel-example/hypervisor'
make -C kernel
make[1]: Entering directory '/home/alon/kvm-test/kvm-kernel-example/kernel'
make -C syscalls/ syscalls.a
make[2]: Entering directory '/home/alon/kvm-test/kvm-kernel-example/kernel/syscalls'
make[2]: 'syscalls.a' is up to date.
make[2]: Leaving directory '/home/alon/kvm-test/kvm-kernel-example/kernel/syscalls'
make -C hypercalls/ hypercalls.a
make[2]: Entering directory '/home/alon/kvm-test/kvm-kernel-example/kernel/hypercalls'
make[2]: 'hypercalls.a' is up to date.
make[2]: Leaving directory '/home/alon/kvm-test/kvm-kernel-example/kernel/hypercalls'
make -C mm/ mm.a
make[2]: Entering directory '/home/alon/kvm-test/kvm-kernel-example/kernel/mm'
make[2]: 'mm.a' is up to date.
make[2]: Leaving directory '/home/alon/kvm-test/kvm-kernel-example/kernel/mm'
make -C elf/ elf.a
make[2]: Entering directory '/home/alon/kvm-test/kvm-kernel-example/kernel/elf'
make[2]: 'elf.a' is up to date.
make[2]: Leaving directory '/home/alon/kvm-test/kvm-kernel-example/kernel/elf'
make -C utils/ utils.a
make[2]: Entering directory '/home/alon/kvm-test/kvm-kernel-example/kernel/utils'
cc -nostdlib -Os -Wall -Werror -fPIE -pie -masm=intel -I.. -c -MMD -MP string.c
string.c: In function ‘strlen’:
string.c:6:10: error: ‘strnlen’ specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
    6 |   return strnlen(s, ~0ll);
      |          ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [../template.mk:16: string.o] Error 1
make[2]: Leaving directory '/home/alon/kvm-test/kvm-kernel-example/kernel/utils'
make[1]: *** [Makefile:24: utils/utils.a] Error 2
make[1]: Leaving directory '/home/alon/kvm-test/kvm-kernel-example/kernel'
make: *** [Makefile:6: kernel] Error 2

**Comment by david942j** [comment]
Could you confirm: 
replace `strnlen(s, ~0ll)` with `strnlen(s, (1ull << 63) - 1)` 
is able to get rid of the error?

**Comment by alonwillmakeit** [comment]
Problem 100% fixed 
Thanks alot :)

alon @ ~/projects/kvm-kernel-example - [master] $ **hypervisor/hypervisor.elf kernel/kernel.bin user/orw.elf /etc/os-release**
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
+++ exited with 0 +++

**Comment by david942j** [comment]
Fixed on the master branch, thanks for your report!
