### ISSUE TITLE
Incorrect RSP value?

### ISSUE THREAD

**Issue by mythilivutukuru** [david942j/kvm-kernel-example#7]
Many thanks for making this code available. I have one doubt on the working of the code.

In the function setup_regs in hypervisor.c, shouldn't the value of RSP be set to  MAX_KERNEL_SIZE + 0x5000 + KERNEL_STACK_SIZE instead of  MAX_KERNEL_SIZE +KERNEL_STACK_SIZE? My understanding of the memory layout of the guest is that you place the kernel, then the page table, and then the kernel stack. With the current setting of RSP, the stack is writing to the same page that is used for the page tables. Of course, the code works correctly even now, because the page table and the kernel stack are both not using the full page. But, if they did, it would cause issues. 

Please let me know if my understanding is correct.

**Comment by david942j** [comment]
Thanks for the finding!

You are right. Though it took me minutes to figure out what I was doing 😂.

ITOH I found the paging only needs 3 pages instead of 5, so guess I can modify 0x5000 to 0x3000 (surly I will give it a name instead of hardcode this time). Do you think this is right? It's been a long time so I'm not sure.

**Comment by mythilivutukuru** [comment]
No, you’ll need 5 pages, not 3. Initially, 3 pages are used. But two more pages are used later on in the kernel code to add mapping’s for high virtual addresses for kernel mappings. So 5 pages are required.

**Comment by david942j** [comment]
Thanks for the explanation 😂
I will add comment on this.

**Comment by mythilivutukuru** [comment]
Thanks. 

I am teaching a course on virtualization and would like to use your code in one of my programming assignments, to get students to learn and implement systems calls and hypercalls. I’ll of course credit you and this GitHub repo. Please let me know if this is alright. Thanks.

**Comment by david942j** [comment]
Sure! It's my honor that this project can used in education purpose 😄
